version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: frontend/docker
      dockerfile: development/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/app:/app
    command: sh -c "npm i ; npm run dev -- --host"
  gateway:
    container_name: gateway
    build:
      context: gateway/docker
      dockerfile: development/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
  backend-nginx:
    container_name: backend-nginx
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    environment:
      PHP_FPM_ADDRESS: backend-php-fpm:9000
    volumes:
      - ./backend/app:/app
  backend-php-fpm:
    container_name: backend-php-fpm
    build:
      context: backend/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./backend/app:/app
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: movie_subtitles_pass
    volumes:
      - mv_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend-php-cli:
    container_name: backend-php-cli
    build:
      context: backend/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./backend/app:/app
volumes:
  mv_pgdata: